messages:
  clan_created_successfully: "&aОтлично! Вы создали новый клан: %clan_name%"
  clan_creation_error_name_length: "&cОшибка: Название клана должно содержать от 4 до 16 символов."
  clan_creation_error_invalid_characters: "&cОшибка: Название клана содержит недопустимые символы. Используйте только буквы и цифры."
  clan_creation_error_clan_exists: "&cОшибка: Клан с таким названием уже существует."
  clan_creation_error_insufficient_balance: "&cОшибка: Недостаточно средств для создания клана. Требуется: %clan_creation_cost%"
  clan_creation_error_already_member: "&cОшибка: Вы уже состоите в клане."
  not_clan_leader: "&cОшибка: Вы не являетесь лидером клана."
  clan_dissolved_by_leader: "&cКлан был распущен лидером."
  clan_dissolved_successfully: "&aКлан успешно распущен."
  no_clan_membership: "&cОшибка: Вы не состоите в клане."
  clan_level_up: "&aПоздравляем! Ваш клан достиг уровня &e%new_level%&a! Продолжайте в том же духе!"
  clan_investment: "&6Игрок &e%player%&6 внес &e%amount%$&6 в казну клана"
  clan_balance_display: "&6Баланс клана: &e%clan_balance%$"
  clan_withdrawal: "&6Игрок &e%player%&6 вывел &e%amount%$&6 из казны клана"
  invite_error_member_exists: "&cОшибка: &7Игрок &e%player%&7 уже является членом клана."
  invite_error_max_members_reached: "&cОшибка: &7В клане &e%clan_name%&7 достигнут максимум участников."
  invite_error_player_not_online: "&cОшибка: &7Игрок &e%player%&7 не найден в сети."
  invite_error_no_clan: "&cОшибка: &7У вас нет клана."
  invite_notification: "&7Игрок &e%sender%&7 приглашает вас в клан &e%clan_name%&7."
  invite_sent_success: "&aПриглашение успешно отправлено игроку &e%invited_player%&a."
  clan_exit_success: "&7Вы успешно покинули клан '%clan_name%'."
  exit_notification: "&7Игрок &e%player%&7 покинул клан."
  player_kicked: "&7Игрок &e%player%&7 был исключен из клана '%clan_name%'."
  kick_notification: "&7Игрок &e%player%&7 был исключен из клана."
  clan_pvp_enabled: "&cПвп в клане &aвключено"
  clan_pvp_disabled: "&cПвп в клане &4выключено"
  home_set_message: "Новая точка дома клана установлена"
  teleport_to_home_success: "Успешная телепортация к точке дома"
  home_delete_error: "Ошибка, точка дома не была установлена для этого клана"
  home_deleted: "Точка дома успешно удалена"
  invite_accepted: "Приглашение в клан успешно принято"
  player_joined_clan: "Игрок %player% вступил в клан!"
clans:
invite-command-delay: 30
clan-creation-cost: 100
clan-name-placeholder: "&d%clan_name%"
storageData: